export const projectsData = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description: "A full-stack e-commerce application with product filtering, cart management, and checkout process.",
    longDescription: "Built with React, Redux, and Node.js. Features include real-time inventory updates, secure payment integration, and responsive design.",
    image: "https://images.unsplash.com/photo-1557821552-17105176677c?w=500&h=300&fit=crop",
    technologies: ["React", "Redux", "Node.js", "MongoDB", "Stripe", "Tailwind CSS"],
    github: "https://github.com/saifullahmsd/ecommerce",
    live: "https://ecommerce-demo.vercel.app",
    category: "Full Stack",
    featured: true,
  },
  {
    id: 2,
    title: "Task Management App",
    description: "A collaborative task management tool with real-time updates and team features.",
    longDescription: "Developed with React and Firebase. Users can create projects, assign tasks, set deadlines, and collaborate in real-time.",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=500&h=300&fit=crop",
    technologies: ["React", "Firebase", "Tailwind CSS", "React Router"],
    github: "https://github.com/saifullahmsd/task-manager",
    live: "https://task-manager-app.vercel.app",
    category: "Frontend",
    featured: true,
  },
  {
    id: 3,
    title: "Weather Dashboard",
    description: "Real-time weather information with beautiful UI and location-based forecasts.",
    longDescription: "An interactive weather app using OpenWeather API. Features include 5-day forecast, weather alerts, and multiple city support.",
    image: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&h=300&fit=crop",
    technologies: ["React", "API Integration", "Tailwind CSS", "Chart.js"],
    github: "https://github.com/saifullahmsd/weather-app",
    live: "https://weather-dashboard.vercel.app",
    category: "Frontend",
    featured: true,
  },
  {
    id: 4,
    title: "Portfolio Website",
    description: "Modern and responsive personal portfolio website showcasing projects and skills.",
    longDescription: "Built with React and Framer Motion animations. Features smooth scrolling, dark mode, and mobile-responsive design.",
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=500&h=300&fit=crop",
    technologies: ["React", "Framer Motion", "Tailwind CSS", "Vite"],
    github: "https://github.com/saifullahmsd/portfolio-2025",
    live: "https://portfolio-2025-eta-eosin.vercel.app",
    category: "Frontend",
    featured: false,
  },
  {
    id: 5,
    title: "Social Media Analytics",
    description: "Analytics dashboard for tracking social media metrics and engagement.",
    longDescription: "A comprehensive analytics tool with charts, graphs, and real-time data visualization using Chart.js and React.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&h=300&fit=crop",
    technologies: ["React", "Chart.js", "Node.js", "MongoDB", "Tailwind CSS"],
    github: "https://github.com/saifullahmsd/social-analytics",
    live: "https://social-analytics.vercel.app",
    category: "Full Stack",
    featured: false,
  },
  {
    id: 6,
    title: "AI Chat Bot",
    description: "Intelligent chatbot powered by AI for customer support and engagement.",
    longDescription: "An AI-powered chatbot using OpenAI API. Features natural language processing and context-aware responses.",
    image: "https://images.unsplash.com/photo-1526374965328-7f5ae4e8b914?w=500&h=300&fit=crop",
    technologies: ["React", "OpenAI API", "Node.js", "Express", "Tailwind CSS"],
    github: "https://github.com/saifullahmsd/ai-chatbot",
    live: "https://ai-chatbot.vercel.app",
    category: "Full Stack",
    featured: false,
  },
];
